"""Build web/i18n-en.js from en.json and check it against keys.json.

    python docs/i18n/build.py

Reports keys that have no English yet (they fall back to Japanese at runtime) and entries
whose {placeholders} differ from the Japanese key, which would break interpolation.
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
PLACEHOLDER = re.compile(r"\{[a-zA-Z0-9_]+\}")


def main():
    keys = json.load(io.open(os.path.join(HERE, "keys.json"), encoding="utf-8"))
    en = json.load(io.open(os.path.join(HERE, "en.json"), encoding="utf-8"))
    missing = [k for k in keys if k not in en]
    unused = [k for k in en if k not in keys]
    bad = [k for k, v in en.items() if sorted(PLACEHOLDER.findall(k)) != sorted(PLACEHOLDER.findall(v))]
    body = json.dumps(en, ensure_ascii=False, indent=1, sort_keys=True)
    out = (
        "/* English dictionary for web/i18n.js: Japanese source string -> English. Generated by\n"
        "   docs/i18n/build.py from docs/i18n/en.json; edit the JSON, not this file. */\n"
        "window.OY_I18N_EN = " + body + ";\n"
    )
    io.open(os.path.join(ROOT, "web", "i18n-en.js"), "w", encoding="utf-8", newline="\n").write(out)
    print(f"{len(en)} entries written to web/i18n-en.js")
    if missing:
        print(f"{len(missing)} keys without English:")
        for k in missing:
            print("  -", json.dumps(k, ensure_ascii=False))
    if unused:
        print(f"{len(unused)} English entries no longer used:")
        for k in unused:
            print("  -", json.dumps(k, ensure_ascii=False))
    if bad:
        print(f"{len(bad)} entries whose placeholders differ:")
        for k in bad:
            print("  -", json.dumps(k, ensure_ascii=False), "->", json.dumps(en[k], ensure_ascii=False))
    sys.exit(1 if (missing or bad) else 0)


if __name__ == "__main__":
    main()
